on:
  workflow_dispatch

jobs:
  build-and-run:
    runs-on: ubuntu-latest
#TODO: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
    steps:
      - name: Check out code
        uses: actions/checkout@v3
#TODO: can we split this into pieces?
      - name: Build and run
        env:
          VAMSYS_USERNAME: ${{ secrets.VAMSYS_USERNAME }}
          VAMSYS_PASSWORD: ${{ secrets.VAMSYS_PASSWORD }}
        run: |
          #export | sed 's/./& /g'
          podman build -t gizmo71/vamsys-scraper -f Dockerfile
          echo "config = {'username': '${VAMSYS_USERNAME}', 'password': '${VAMSYS_PASSWORD}'}" >$GITHUB_WORKSPACE/vamsys.py
          podman run --rm -v$GITHUB_WORKSPACE:/data --shm-size="2g" gizmo71/vamsys-scraper python3 /data/scrape.py
          podman run --rm -v$GITHUB_WORKSPACE:/data gizmo71/vamsys-scraper python3 /data/process.py
          rm $GITHUB_WORKSPACE/vamsys.py
          mkdir dist
          cp routes.html routes.js *.vamsys.js dist/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
